# Generated by Django 3.0.8 on 2020-08-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='아이디')),
                ('user_password', models.CharField(max_length=20, verbose_name='패스워드')),
                ('user_email', models.EmailField(max_length=40, verbose_name='이메일')),
                ('user_registerdate', models.DateTimeField(auto_now_add=True, verbose_name='가입일자')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_name', models.CharField(max_length=40, verbose_name='아이디')),
                ('pur_jejo_num', models.CharField(max_length=15, verbose_name='아이디')),
                ('pur_company', models.CharField(max_length=40, verbose_name='아이디')),
                ('pur_date', models.DateTimeField(auto_now_add=True, verbose_name='가입일자')),
                ('pur_jejodate', models.DateTimeField(auto_now_add=True, verbose_name='가입일자')),
                ('pur_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jangbogo.User')),
            ],
        ),
    ]
