# Generated by Django 3.0.8 on 2020-08-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jangbogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pur_company',
            field=models.CharField(max_length=40, verbose_name='제조업체명'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pur_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='구매일자'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pur_jejo_num',
            field=models.CharField(max_length=15, verbose_name='제품제조번호'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pur_jejodate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='제조일자'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pur_name',
            field=models.CharField(max_length=40, verbose_name='제품명'),
        ),
    ]
