# Generated by Django 3.0.8 on 2020-08-14 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jangbogo', '0003_purchase_pur_expire_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pur_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 17, 25, 59, 307961), verbose_name='구매일자'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pur_jejodate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 17, 25, 59, 307961), verbose_name='제조일자'),
        ),
    ]
